version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: ood-keycloak
    hostname: ${HOSTNAME}
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=dev-file
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HTTP_ENABLED=false
      - KC_HTTPS_PORT=8443
      - KC_HOSTNAME_STRICT=false
      - KC_HEALTH_ENABLED=true
      - HOSTNAME=${HOSTNAME}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OOD_HTTPS_PORT=${OOD_HTTPS_PORT}
    ports:
      - "8443:8443"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realm-import.json.template:/opt/keycloak/data/import/realm-import.json.template:ro
      - ./docker/init-keycloak.sh:/opt/keycloak/bin/init-keycloak.sh:ro
      - ./docker/add-users-keycloak.sh:/opt/keycloak/bin/add-users-keycloak.sh:ro
      - ./templates:/opt/keycloak/templates:ro
      - ./ssl/keycloak.crt:/opt/keycloak/conf/server.crt.pem:ro
      - ./ssl/keycloak.key:/opt/keycloak/conf/server.key.pem:ro
      - ./themes/ondemand-theme:/opt/keycloak/themes/ondemand-theme:ro
      - keycloak_passwords:/root:rw
    entrypoint: ["/bin/bash", "/opt/keycloak/bin/init-keycloak.sh"]
    user: "0"
    networks:
      - ood-network

  ondemand:
    build:
      context: .
      dockerfile: Dockerfile.ood
    image: ood-with-keycloak:latest
    container_name: ood-app
    hostname: ${HOSTNAME}
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/ood_portal.yml.template:/etc/ood/config/ood_portal.yml.template:ro
      - ./config/ondemand.yml:/etc/ood/config/ondemand.d/ondemand.yml:ro
      - ./config/public:/var/www/ood/public/custom:ro
      - ./config/public/favicon.ico:/var/www/ood/public/favicon.ico:ro
      - ./config/clusters.d:/etc/ood/config/clusters.d:rw
      - ./config/shell_config.env:/var/www/ood/apps/sys/shell/.env.local:ro
      - ./config/apps:/var/www/ood/apps/usr:ro
      - ./config/motd:/etc/motd:ro
      - ./config/apps/news_bulletin/views/_news_bulletin.html.erb:/etc/ood/config/apps/dashboard/views/widgets/_news_bulletin.erb
      - ./config/apps/news/views/_news.html.erb:/etc/ood/config/apps/dashboard/views/widgets/_news.erb
      - ./config/apps/bulletin_board/views/_bulletin_board.html.erb:/etc/ood/config/apps/dashboard/views/widgets/_bulletin_board.html.erb
      - ./templates/passwd:/tmp/template_passwd:ro
      - ./templates/shadow:/tmp/template_shadow:ro
      - ./templates/group:/tmp/template_group:ro
      - ./docker/setup-users-ood.sh:/usr/local/bin/setup-users-ood.sh:ro
      - ./docker/setup-ssh.sh:/usr/local/bin/setup-ssh.sh:ro
      - ./ssl/ood.crt:/etc/ssl/certs/ood.crt:ro
      - ./ssl/ood.key:/etc/ssl/private/ood.key:ro
      - type: bind
        source: /c/home
        target: /c/home
        bind:
          propagation: rshared
      - ood_data:/var/lib/ondemand
      - ood_logs:/var/log/ondemand
      - keycloak_passwords:/mnt/keycloak_passwords:ro
    networks:
      - ood-network
    environment:
      - OOD_PORTAL_GENERATOR=true
      - HOSTNAME=${HOSTNAME}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_CRYPTO_PASSPHRASE=${OIDC_CRYPTO_PASSPHRASE}
      - MOTD_PATH="/etc/motd" 
      - MOTD_FORMAT="markdown" 
    entrypoint: ["/bin/bash", "-c", "/usr/local/bin/setup-users-ood.sh && exec /usr/sbin/httpd -DFOREGROUND"]
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://${HOSTNAME}/public/favicon.ico || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  keycloak_data:
    driver: local
  keycloak_passwords:
    driver: local
  ood_data:
    driver: local
  ood_logs:
    driver: local

networks:
  ood-network:
    driver: bridge
